---
- name: Update packages and reboot if necessary
  hosts: remote_servers
  become: yes

  tasks:
    - name: Gather OS facts
      setup:
        gather_subset:
          - "!all"
          - "!any"
          - "os"

    - name: Update packages and reboot if necessary for Debian-based systems
      block:
        - name: Update packages (Debian)
          apt:
            update_cache: yes
            upgrade: safe
          register: apt_result

        - name: Check if reboot is required (Debian)
          stat:
            path: /var/run/reboot-required
          register: reboot_required

      when: "'Debian' in ansible_facts['os_family']"

    - name: Update packages and reboot if necessary for RedHat-based systems
      block:
        - name: Update packages (RedHat)
          yum:
            name: "*"
            state: latest
          register: yum_result

        - name: Check if reboot is required (RedHat)
          command: needs-restarting -r
          ignore_errors: true
          register: reboot_required
          changed_when: false

      when: "'RedHat' in ansible_facts['os_family']"

    - name: Reboot server if required
      reboot:
        msg: "Rebooting due to package updates"
        pre_reboot_delay: 60
      when: reboot_required is defined and reboot_required.stat.exists|default(False)
