- name: Disable root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart sshd
- name: Enable SSH login only for specific users
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers user1 user2'
    state: present
  notify: Restart sshd
- name: Disable password authentication via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart sshd
- name: Set login banner
  copy:
    src: login_banner.txt
    dest: /etc/ssh_banner
    mode: '0644'
  notify: Restart sshd
- name: Set logout banner
  copy:
    src: logout_banner.txt
    dest: /etc/logout_banner
    mode: '0644'
  notify: Restart sshd