---
- name: Create VM on vSphere
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    folder: "{{ folder }}"
    name: "{{ vm_name }}"
    template: "{{ template }}"
    state: present
    customization:
      existing_vm: "{{ vm_name }}"
      hostname: "{{ vm_name }}"
      domain: "{{ domain }}"
    networks:
      - name: "{{ network }}"
        device_type: vmxnet3
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      scsi: paravirtual
      boot_firmware: bios
    disk:
      - size_gb: "{{ disk_size_gb }}"
        type: thin
        datastore: "{{ datastore }}"
    wait_for_ip_address: yes
  register: vm_deploy_result

- name: Show VM deployment result
  debug:
    var: vm_deploy_result
