---
- name: Install Uyuni proxy
  hosts: uyuni_proxy
  become: true
  tasks:
    - name: Import Uyuni GPG key
      rpm_key:
        key: https://www.uyuni-project.org/uyuni.asc
        state: present

    - name: Add Uyuni repository
      yum_repository:
        name: uyuni-proxy-stable
        description: Uyuni Proxy Stable
        baseurl: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-POOL-x86_64-Media1/
        gpgcheck: yes
        gpgkey: https://www.uyuni-project.org/uyuni.asc
        state: present

    - name: Install Uyuni proxy pattern
      yum:
        name: patterns-uyuni_proxy
        state: present

    - name: Setup Uyuni proxy
      command: uyuni-proxy-setup --wizard

    - name: Enable and start Uyuni proxy services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - cobblerd
        - dhcpd
        - spacewalksd
        - tftp
        - vsftpd
       
