---
- name: Install Uyuni server
  hosts: uyuni_server
  become: true
  tasks:
    - name: Import Uyuni GPG key
      rpm_key:
        key: https://www.uyuni-project.org/uyuni.asc
        state: present

    - name: Add Uyuni repository
      yum_repository:
        name: uyuni-server-stable
        description: Uyuni Server Stable
        baseurl: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
        gpgcheck: yes
        gpgkey: https://www.uyuni-project.org/uyuni.asc
        state: present

    - name: Install Uyuni server pattern
      yum:
        name: patterns-uyuni_server
        state: present

    - name: Setup Uyuni server
      command: uyuni-setup --wizard

    - name: Enable and start Uyuni services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - postgresql
        - tomcat
        - uyuni-check-database
        - apache2
        - cobblerd
        - dhcpd
        - spacewalksd
        - tftp
        - vsftpd
        - salt-master
        - spacewalk-services
