---
- name: Test SAP application on Azure
  hosts: sap_app_servers
  gather_facts: yes
  tasks:
    - name: Check connectivity between SAP application and SAP HANA database
      block:
        - name: Ping SAP HANA database
          ansible.builtin.ping:
            data: "{{ sap_hana_private_ip }}"
          register: ping_result

        - name: Display ping results
          ansible.builtin.debug:
            var: ping_result.ping

    - name: Check network latency
      block:
        - name: Measure network latency using MTR
          ansible.builtin.command:
            cmd: mtr -c 10 -r -w "{{ sap_hana_private_ip }}"
          register: mtr_result

        - name: Display MTR results
          ansible.builtin.debug:
            var: mtr_result.stdout_lines

    - name: Check response time of SAP application
      block:
        - name: Measure response time using curl
          ansible.builtin.command:
            cmd: curl -o /dev/null -s -w '%{time_total}\n' "http://{{ sap_app_public_ip }}/sap"
          register: curl_result

        - name: Display response time
          ansible.builtin.debug:
            var: curl_result.stdout

    - name: Collect system information
      block:
        - name: Check CPU usage
          community.general.system:
          register: system_info

        - name: Display CPU usage
          ansible.builtin.debug:
            var: system_info.cpu.percent

        - name: Check memory usage
          ansible.builtin.setup:
            gather_subset:
              - '!all'
              - '!min'
              - hardware

        - name: Display memory usage
          ansible.builtin.debug:
            var: ansible_memtotal_mb

    - name: Check disk I/O performance
      block:
        - name: Measure disk I/O performance using fio
          ansible.builtin.command:
            cmd: fio --name=test --rw=randread --size=1G --time_based --runtime=30s --ioengine=libaio --iodepth=32 --numjobs=4
          register: fio_result

        - name: Display fio results
          ansible.builtin.debug:
            var: fio_result.stdout_lines

    - name: Check network throughput
      block:
        - name: Measure network throughput using iperf
          ansible.builtin.command:
            cmd: iperf -c {{ sap_hana_private_ip }} -t 30 -P 4 -i 1
          register: iperf_result

        - name: Display iperf results
          ansible.builtin.debug:
            var: iperf_result.stdout_lines